control 'V-61693' do
  title 'Oracle must back up user-level information per a defined frequency.'
  desc  "Information system backup is a critical step in maintaining data
  assurance and availability.

      User-level information is data generated by information system and/or
  application users. In order to assure availability of this data in the event of
  a system failure, DoD organizations are required to ensure user-generated data
  is backed up at a defined frequency. This includes data stored on file systems,
  within databases or within any other storage media.

      Applications performing backups must be capable of backing up user-level
  information per the DoD-defined frequency.

      Databases that do not backup information regularly risk the loss of that
  information in the event of a system failure. Most databases contain
  functionality to allow regular backups; it is important that this functionality
  is enabled and configured correctly to prevent data loss.
  "
  impact 0.5
  tag "gtitle": 'SRG-APP-000145-DB-000095'
  tag "gid": 'V-61693'
  tag "rid": 'SV-76183r2_rule'
  tag "stig_id": 'O121-C2-012200'
  tag "fix_id": 'F-67609r1_fix'
  tag "cci": ['CCI-000535']
  tag "nist": ['CP-9 (a)', 'Rev_4']
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  tag "check": "Review DBMS settings and site documentation to determine
  whether Oracle is configured to back up user-level data according to a defined
  frequency.

  If it is not, this is a finding.

  (The V$RMAN_STATUS view displays the finished and on-going RMAN jobs. For
  on-going jobs, this view displays progress and status.)"
  tag "fix": "Configure the Oracle DBMS to back up user-level data on a defined
  frequency."
  describe 'A manual review is required to ensure Oracle backs up user-level information per a defined frequency' do
    skip 'A manual review is required to ensure Oracle backs up user-level information per a defined frequency'
  end
end
