control 'V-61649' do
  title "The system must provide the capability to automatically process audit
  records for events of interest based upon selectable event criteria."
  desc "Before a security review, information systems and/or applications with
  an audit reduction capability may remove many audit records known to have
  little security significance.

      This is generally accomplished by removing records generated by specified
  classes of events, such as records generated by nightly backups.

      An audit reduction capability provides support for near real-time audit
  review and analysis based on policy requirements regarding what must be audited
  on the system and after-the-fact investigations of security incidents. It is
  important to recognize audit reduction does not alter original audit records.

      Audit reduction and reporting tools do not alter original audit records.

      To leverage the complete capability of audit reduction, the application
  must possess the ability to specify and automatically process certain event
  criteria that are selectable in nature. In other words, a system administrator
  (SA) may be performing a manual review of audit data to identify a particular
  problem. The SA has determined that backup activity and network connections
  from a particular host comprise the bulk of the events. However, these events
  are not related to the activity being investigated. The application must be
  able to automatically process these audit records for audit reduction purposes
  rather than making the administrator manually process them.

      The lack of audit reduction and reporting in a database can require the
  DBA, or others responsible for reviewing audit logs, to sort through large
  amounts of data in order to find relevant records. This can cause important
  audit records to be missed.

      Oracle offers the choice of storing audit data internally in database
  tables, or in external files.  The WHERE clause in the SELECT statement
  provides the necessary functionality for a table-based audit.  For an audit
  based on external files (or for a table-based audit trail archived to external
  files) Oracle Database does not provide tools for retrieving and managing the
  data once written.  Therefore, an external tool is needed.
  "
  impact 0.5
  tag "gtitle": 'SRG-APP-000115-DB-000055'
  tag "gid": 'V-61649'
  tag "rid": 'SV-76139r2_rule'
  tag "stig_id": 'O121-C2-008900'
  tag "fix_id": 'F-67563r2_fix'
  tag "cci": ['CCI-000158']
  tag "nist": ['AU-7 (1)', 'Rev_4']
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  tag "check": "Review the system (OS, applications external to Oracle, and/or
  a separate log aggregation and query server) to determine whether it provides
  the ability to automatically process audit records for events based on
  selectable event criteria. If the system does not provide these abilities, they
  may be handled by a separate application.

  If the ability to automatically process audit records for events based on
  selectable event criteria does not exist, this is a finding."
  tag "fix": "Utilize a tool, application or service that provides the ability
  to automatically process audit records for events based on selectable event
  criteria."
  describe service('auditd') do
    it { should be_enabled }
    it { should be_running }
  end
end
