control 'V-61969' do
  title "The system must provide a report generation capability for audit
  reduction data."
  desc  "In support of Audit Review, Analysis, and Reporting requirements,
  audit reduction is a technique used to reduce the volume of audit records in
  order to facilitate a manual review.

      Before a security review is conducted, information systems and/or
  applications with an audit reduction capability may remove many audit records
  known to have little security significance. This is generally accomplished by
  removing records generated by specified classes of events, such as records
  generated by nightly backups.

      In order to identify and report on what (repetitive) data has been removed
  via the use of audit reduction, the application must provide a capability to
  generate reports containing what values were removed by the audit reduction.

      Audit reduction does not alter original audit records. An audit reduction
  capability provides support for near real-time audit review and analysis based
  on policy-based requirements and after-the-fact investigations of security
  incidents.

      Reporting tools employing audit reduction methods must not alter the
  original audit data. An example of a tool employing audit reduction methods is
  the Windows Event Viewer tool which is used to view and analyze audit logs on
  Windows systems.

      The lack of reporting tools for audit reduction can require the DBA, or
  others responsible for reviewing audit logs, to sort through large amounts of
  data in order to find relevant records.  This can cause important audit records
  to be missed.
  "
  impact 0.3
  tag "gtitle": 'SRG-APP-000114-DB-000054'
  tag "gid": 'V-61969'
  tag "rid": 'SV-76459r1_rule'
  tag "stig_id": 'O121-C3-008800'
  tag "fix_id": 'F-67889r1_fix'
  tag "cci": ['CCI-001878']
  tag "nist": ['AU-7 a', 'Rev_4']
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  tag "check": "Verify that audit reduction capabilities are in place for the
  Oracle audit data.  Since Oracle has no reduction capability per se, a
  third-party tool or in-house-developed software must be in place to provide
  this functionality.  This must include the ability to report on the excluded
  audit data.

  If this capability has not been implemented, this is a finding."
  tag "fix": "Deploy software capable of performing audit data reduction and of
  reporting on the excluded audit data."
  describe 'A manual review is required to ensure the system provides a report generation capability for audit
    reduction data' do
    skip 'A manual review is required to ensure the system provides a report generation capability for audit
    reduction data'
  end
end
